### ISSUE TITLE
aqi-service fails and crashes weewx when no data is available

### ISSUE THREAD

**Issue by n7qnm** [jonathankoren/weewx-aqi#35] opened 2022-06-10 23:54 UTC
I had a sensor issue and so had no data for an extended period of time.   After not finding any data, the AQI service fails and crashes weewx.  
Jun  4 05:40:19 weewx weewx[20685] INFO weewx.engine: Main loop exiting. Shutting engine down.
Jun  4 05:40:19 weewx weewx[20685] INFO weewx.engine: Shutting down StdReport thread
Jun  4 05:40:19 weewx weewx[20685] INFO user.sdr: shutdown process rtl_433 -M utc -F json
Jun  4 05:40:19 weewx weewx[20685] INFO user.MQTTSubscribe: (Service) Disconnected with result code 0
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__: Caught unrecoverable exception:
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****  list index out of range
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****  Traceback (most recent call last):
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 214, in run
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.CHECK_LOOP, packet=packet))
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      callback(event)
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 634, in check_loop
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      raise BreakLoop
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****  weewx.engine.BreakLoop
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****  Traceback (most recent call last):
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 650, in post_loop
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      self._catchup(self.engine.console.genArchiveRecords)
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 697, in _catchup
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      for record in generator(lastgood_ts):
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/drivers/__init__.py", line 30, in genArchiveRecords
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      raise NotImplementedError("Method 'genArchiveRecords' not implemented")
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****  NotImplementedError: Method 'genArchiveRecords' not implemented
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****  Traceback (most recent call last):
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewxd", line 153, in main
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      engine.run()
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 221, in run
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.POST_LOOP))
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      callback(event)
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 652, in post_loop
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      self._software_catchup()
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 715, in _software_catchup
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      self.engine.dispatchEvent(weewx.Event(weewx.NEW_ARCHIVE_RECORD,
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      callback(event)
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/user/aqi/service.py", line 355, in new_archive_record
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      self.aqi_standard.calculate_aqi(pollutant, required_unit, joined)
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/user/aqi/standards.py", line 57, in calculate_aqi
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      return self.calculators[pollutant].calculate(pollutant, observation_unit, observations)
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/user/aqi/calculators.py", line 172, in calculate
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      last_valid_index = get_last_valid_index(observations, self.duration_in_secs)
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****    File "/home/weewx/bin/user/aqi/calculators.py", line 38, in get_last_valid_index
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****      first_invalid_timestamp = observations[0][0] - duration_in_secs
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****  IndexError: list index out of range
Jun  4 05:40:23 weewx weewx[20685] CRITICAL __main__:     ****  Exiting.

**Comment by xslima00** [comment] 2022-08-19 17:41
I had very similar issue

**Comment by jonathankoren** [comment] 2023-01-02 07:31
dupe of #39
use v1.4.1

**Closed by jonathankoren** 2023-01-02 07:31 UTC
